### ISSUE TITLE
can`t  run 'yarn run build'

### ISSUE THREAD

**Issue by aibinMr** [theatre-js/theatre#364]
development environment：
os：win11；node 16.10.0 ,yarn 3.2.0

when i run ‘yarn run build’， a error is there
`$ yarn run build
$ yarn run build:ts
$ yarn workspace theatre run build
$ yarn workspace $'@theatre/dataverse' run build
$ yarn workspace $'@theatre/react' run build
$ yarn workspace $'@theatre/browser-bundles' run build
$ yarn workspace $'@theatre/r3f' run build
 > error: The entry point "F:\\kingfisher\\ainimation\\theatre\\packages\\react\\src\\index.ts" cannot be marked as external

F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1449
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: The entry point "F:\\kingfisher\\ainimation\\theatre\\packages\\react\\src\\index.ts" cannot be marked as external
    at failureErrorWithLog (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1449:15)
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1129:7)
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1236:14
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The entry point "F:\\\\kingfisher\\\\ainimation\\\\theatre\\\\packages\\\\react\\\\src\\\\index.ts" cannot be marked as external'
    }
  ],
  warnings: []
}
ERROR: "build:js" exited with 1.
file:///F:/kingfisher/ainimation/theatre/node_modules/zx/index.mjs:49
        let output = new ProcessOutput({
                     ^

ProcessOutput [Error]:  > error: The entry point "F:\\kingfisher\\ainimation\\theatre\\packages\\react\\src\\index.ts" cannot be marked as external

F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1449
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: The entry point "F:\\kingfisher\\ainimation\\theatre\\packages\\react\\src\\index.ts" cannot be marked as external
    at failureErrorWithLog (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1449:15)
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1129:7)
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:1236:14
    at F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (F:\kingfisher\ainimation\theatre\packages\react\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The entry point "F:\\\\kingfisher\\\\ainimation\\\\theatre\\\\packages\\\\react\\\\src\\\\index.ts" cannot be marked as external'
    }
  ],
  warnings: []
}
ERROR: "build:js" exited with 1.
    at file:///F:/kingfisher/ainimation/theatre/scripts/build.mjs:36:29
    at ChildProcess.<anonymous> (file:///F:/kingfisher/ainimation/theatre/node_modules/zx/index.mjs:49:22)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
`

**Comment by tomorrowevening** [comment]
`run` is associated with npm, so either use `yarn build` or `npm run build`

**Comment by rok4f** [comment]
> `run` is associated with npm, so either use `yarn build` or `npm run build`

Same error raises using `yarn build` or `npm run build`

**Comment by rok4f** [comment]
This error is actually within the build command: `yarn workspace @theatre/react run build:js` which is defined in `packages/react/package.json`:
