### ISSUE TITLE
Error: Extension id "@theatre/r3f" is already defined

### ISSUE THREAD

**Issue by marraleks** [theatre-js/theatre#399]
Setting up the r3f extension in Next.js generates this error: 

`Error: Extension id "@theatre/r3f" is already defined`

**Comment by Yinglinhan** [comment]
`error - Error: Extension id "@theatre/r3f" is already defined
    at /Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51935:15
    at Object.payload (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51460:9)
    at studioReducer (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:49830:22)
    at Object.dispatch (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51124:22)
    at StudioStore.tempTransaction (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51474:22)
    at Studio.tempTransaction (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51904:24)
    at Studio.transaction (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51907:17)
    at Studio.extend (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51928:10)
    at TheatreStudio.extend (/Users/han/Desktop/Threez/starter/node_modules/@theatre/studio/dist/index.js:51563:17)
    at eval (webpack-internal:///./src/pages/index.jsx:36:56) {
  page: '/'
}`

I have this problem too, I need to restart project to make it disappear. but always pop up when refresh.

**Comment by Yinglinhan** [comment]
https://github.com/theatre-js/theatre/issues/303  this is the way to solve this problem

> Setting up the r3f extension in Next.js generates this error:
> 
> `Error: Extension id "@theatre/r3f" is already defined`
